import { adminDb } from '@/lib/firebase/admin';
import { UserRole } from '@/types';
import { FieldValue } from 'firebase-admin/firestore';

export type AuditAction =
  | 'ASSET_CREATED' | 'ASSET_UPDATED' | 'ASSET_RETIRED' | 'ASSET_DELETED' | 'ASSETS_IMPORTED'
  | 'ASSET_NOTE_ADDED' | 'ASSET_NOTE_DELETED'
  | 'MAINTENANCE_ADDED' | 'MAINTENANCE_UPDATED' | 'MAINTENANCE_DELETED'
  | 'ASSET_CHECKED_OUT' | 'ASSET_CHECKED_IN'
  | 'WARRANTY_CREATED' | 'WARRANTY_UPDATED' | 'WARRANTY_DELETED'
  | 'WARRANTY_ALERT_SENT'
  | 'REQUEST_SUBMITTED' | 'REQUEST_APPROVED' | 'REQUEST_REJECTED'
  | 'USER_INVITED' | 'USER_UPDATED' | 'USER_DEACTIVATED' | 'USER_DELETED'
  | 'INVITE_SENT' | 'INVITE_ACCEPTED' | 'INVITE_REVOKED'
  | 'ORGANIZATION_CREATED' | 'ORGANIZATION_UPDATED' | 'ORGANIZATION_SELF_SERVE_CREATED'
  | 'SUBSCRIPTION_UPDATED'
  | 'SUBSCRIPTION_PACKAGE_ASSIGNED' | 'SUBSCRIPTION_FEATURE_UPDATED'
  | 'PACKAGE_CREATED' | 'PACKAGE_UPDATED' | 'PACKAGE_DELETED'
  | 'PAYMENT_RECORDED' | 'PAYMENT_DELETED'
  | 'TRANSFER_MODE_ENTERED' | 'TRANSFER_MODE_EXITED'
  | 'TICKET_CREATED' | 'TICKET_UPDATED' | 'TICKET_REPLIED' | 'TICKET_CLOSED' | 'TICKET_RESOLVED'
  | 'INVENTORY_ITEM_CREATED' | 'INVENTORY_ITEM_UPDATED' | 'INVENTORY_ITEM_DELETED'
  | 'INVENTORY_TRANSACTION_CREATED'
  | 'INVENTORY_AUDIT_STARTED' | 'INVENTORY_AUDIT_COMPLETED'
  | 'CONFIG_STATUS_CREATED' | 'CONFIG_STATUS_UPDATED' | 'CONFIG_STATUS_DELETED'
  | 'CONFIG_LOCATION_CREATED' | 'CONFIG_LOCATION_UPDATED' | 'CONFIG_LOCATION_DELETED'
  | 'CONFIG_CATEGORY_CREATED' | 'CONFIG_CATEGORY_UPDATED' | 'CONFIG_CATEGORY_DELETED';

interface LogParams {
  organizationId: string;
  userId: string;
  role: UserRole;
  action: AuditAction;
  module: string;
  recordId?: string;
  oldValue?: Record<string, unknown>;
  newValue?: Record<string, unknown>;
  transferMode?: boolean;
}

export async function writeAuditLog(params: LogParams): Promise<void> {
  await adminDb.collection('auditLogs').add({
    ...params,
    timestamp: FieldValue.serverTimestamp(),
  });
}
