import 'server-only';
import { supabaseAdmin } from '@/lib/supabase/admin';
import { UserRole } from '@/types';

export type AuditAction =
  | 'ASSET_CREATED' | 'ASSET_UPDATED' | 'ASSET_RETIRED' | 'ASSET_DELETED' | 'ASSETS_IMPORTED'
  | 'ASSET_NOTE_ADDED' | 'ASSET_NOTE_DELETED'
  | 'MAINTENANCE_ADDED' | 'MAINTENANCE_UPDATED' | 'MAINTENANCE_DELETED'
  | 'ASSET_CHECKED_OUT' | 'ASSET_CHECKED_IN'
  | 'WARRANTY_CREATED' | 'WARRANTY_UPDATED' | 'WARRANTY_DELETED'
  | 'WARRANTY_ALERT_SENT'
  | 'REQUEST_SUBMITTED' | 'REQUEST_APPROVED' | 'REQUEST_REJECTED'
  | 'USER_INVITED' | 'USER_UPDATED' | 'USER_DEACTIVATED' | 'USER_DELETED'
  | 'INVITE_SENT' | 'INVITE_ACCEPTED' | 'INVITE_REVOKED'
  | 'ORGANIZATION_CREATED' | 'ORGANIZATION_UPDATED' | 'ORGANIZATION_DELETED' | 'ORGANIZATION_SELF_SERVE_CREATED' | 'ORG_CONFIG_UPDATED'
  | 'SUBSCRIPTION_UPDATED' | 'SUBSCRIPTION_AUTO_EXPIRED'
  | 'SUBSCRIPTION_PACKAGE_ASSIGNED' | 'SUBSCRIPTION_FEATURE_UPDATED'
  | 'PACKAGE_CREATED' | 'PACKAGE_UPDATED' | 'PACKAGE_DELETED'
  | 'PAYMENT_RECORDED' | 'PAYMENT_DELETED'
  | 'PAYMENT_LOG_CREATED' | 'PAYMENT_LOG_DELETED'
  | 'TRANSFER_MODE_ENTERED' | 'TRANSFER_MODE_EXITED'
  | 'TICKET_CREATED' | 'TICKET_UPDATED' | 'TICKET_REPLIED' | 'TICKET_CLOSED' | 'TICKET_RESOLVED'
  | 'INVENTORY_ITEM_CREATED' | 'INVENTORY_ITEM_UPDATED' | 'INVENTORY_ITEM_DELETED'
  | 'INVENTORY_TRANSACTION_CREATED'
  | 'INVENTORY_AUDIT_STARTED' | 'INVENTORY_AUDIT_COMPLETED'
  | 'STOCK_AUDIT_STARTED' | 'STOCK_AUDIT_COMPLETED'
  | 'CONFIG_STATUS_CREATED' | 'CONFIG_STATUS_UPDATED' | 'CONFIG_STATUS_DELETED'
  | 'CONFIG_LOCATION_CREATED' | 'CONFIG_LOCATION_UPDATED' | 'CONFIG_LOCATION_DELETED'
  | 'CONFIG_CATEGORY_CREATED' | 'CONFIG_CATEGORY_UPDATED' | 'CONFIG_CATEGORY_DELETED'
  | 'TAX_RATE_CREATED' | 'TAX_RATE_UPDATED' | 'TAX_RATE_DELETED'
  | 'PURCHASE_CREATED' | 'PURCHASE_UPDATED' | 'PURCHASE_DELETED' | 'PURCHASE_RECEIVED' | 'PURCHASE_CANCELLED'
  | 'POS_SESSION_OPENED' | 'POS_SESSION_CLOSED'
  | 'POS_SALE_COMPLETED' | 'POS_SALE_VOIDED' | 'POS_SALE_REFUNDED'
  | 'POS_CUSTOMER_CREATED' | 'POS_CUSTOMER_UPDATED' | 'POS_CUSTOMER_DELETED'
  | 'FAWTARA_CONFIG_UPDATED' | 'FAWTARA_SUBMISSION_SENT' | 'FAWTARA_SUBMISSION_FAILED'
  | 'LIST_ITEM_CREATED' | 'LIST_ITEM_UPDATED' | 'LIST_ITEM_DELETED'
  | 'SPACE_CREATED' | 'SPACE_UPDATED' | 'SPACE_ARCHIVED'
  | 'RECEIPT_CONFIG_UPDATED'
  | 'ORG_LIST_ITEM_CREATED' | 'ORG_LIST_ITEM_UPDATED' | 'ORG_LIST_ITEM_DELETED'
  | 'PROFILE_UPDATED'
  | 'DELIVERY_AGENT_CREATED' | 'DELIVERY_AGENT_UPDATED' | 'DELIVERY_AGENT_DELETED'
  | 'ORDER_CREATED' | 'ORDER_UPDATED' | 'ORDER_STATUS_CHANGED' | 'ORDER_PAYMENT_RECORDED'
  | 'ORDER_DOCUMENT_CONFIG_UPDATED'
  | 'CASH_DRAWER_CONFIG_UPDATED'
  | 'CARD_TERMINAL_CONFIG_UPDATED'
  | 'WARRANTY_CERT_CREATED' | 'WARRANTY_CERT_DELETED'
  | 'WARRANTY_CONFIG_UPDATED'
  | 'CUSTOM_FIELD_CREATED' | 'CUSTOM_FIELD_UPDATED' | 'CUSTOM_FIELD_DELETED'
  | 'SERVICE_JOB_CREATED' | 'SERVICE_JOB_UPDATED' | 'SERVICE_JOB_STATUS_CHANGED' | 'SERVICE_JOB_DELETED'
  | 'SERVICE_JOB_PAYMENT_RECORDED' | 'SERVICE_JOB_INVOICE_GENERATED'
  | 'SERVICE_JOB_PAYMENT_ADDED' | 'SERVICE_JOB_PAYMENT_REMOVED' | 'SERVICE_JOB_ITEMS_ADDED'
  | 'RETAINER_CREATED' | 'RETAINER_UPDATED' | 'RETAINER_STATUS_CHANGED' | 'RETAINER_DELETED'
  | 'RETAINER_INVOICE_CREATED' | 'RETAINER_INVOICE_UPDATED' | 'RETAINER_INVOICE_DELETED'
  | 'RECEPTION_TICKET_CREATED' | 'RECEPTION_TICKET_UPDATED'
  | 'RECEPTION_TICKET_CANCELLED' | 'RECEPTION_TICKET_PAID';

interface LogParams {
  organizationId: string;
  /** Space the action happened in. Required after Script 3 (audit_logs.space_id NOT NULL). */
  spaceId?: string;
  userId: string;
  role: UserRole;
  action: AuditAction;
  module: string;
  recordId?: string;
  oldValue?: Record<string, unknown>;
  newValue?: Record<string, unknown>;
  transferMode?: boolean;
}

function toRow(p: LogParams) {
  return {
    organization_id: p.organizationId,
    space_id: p.spaceId ?? null,
    user_id: p.userId,
    role: p.role,
    action: p.action,
    module: p.module,
    record_id: p.recordId ?? null,
    old_value: p.oldValue ?? null,
    new_value: p.newValue ?? null,
    transfer_mode: p.transferMode ?? null,
  };
}

export async function writeAuditLog(params: LogParams): Promise<void> {
  const { error } = await supabaseAdmin.from('audit_logs').insert(toRow(params));
  if (error) throw error;
}

export function queueAuditLog(params: LogParams): void {
  supabaseAdmin
    .from('audit_logs')
    .insert(toRow(params))
    .then(({ error }) => {
      if (error) console.error('[auditLog] failed to write:', error);
    });
}
